# Generated by Django 3.0.7 on 2020-11-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('humpy_food_app', '0002_auto_20201108_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprofile',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SetProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
