# Generated by Django 3.0.7 on 2020-11-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0005_auto_20201109_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('desc', models.TextField(null=True)),
                ('cate', models.CharField(choices=[('Pasta', 'Pasta'), ('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Sandwich', 'Sandwich'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages')], default='Snacks', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='food/')),
                ('price', models.FloatField(blank=True, null=True)),
                ('types', models.CharField(choices=[('Pasta', 'Pasta'), ('Pizza', 'Pizza'), ('Burger', 'Burger'), ('Sandwich', 'Sandwich'), ('Snacks', 'Snacks'), ('Beverages', 'Beverages')], default='Vegetarian', max_length=100)),
            ],
        ),
    ]
