# Generated by Django 3.0.7 on 2020-11-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0006_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='types',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], default='Vegetarian', max_length=100),
        ),
    ]
