# Generated by Django 3.0.8 on 2020-11-15 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0007_auto_20201112_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
