# Generated by Django 3.0.7 on 2020-11-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0009_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprofile',
            name='image',
            field=models.ImageField(blank=True, default='https://source.unsplash.com/1600x900/?userprofile', null=True, upload_to='image/'),
        ),
    ]
