# Generated by Django 3.0.7 on 2020-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0010_auto_20201122_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/log.png', null=True, upload_to='image/'),
        ),
    ]
