# Generated by Django 3.0.7 on 2020-11-22 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('humpy_food_app', '0011_auto_20201122_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
