# Generated by Django 3.0.8 on 2020-11-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0014_auto_20201124_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track',
            field=models.CharField(choices=[('Accepted', 'Your Order is Accepted'), ('Cook', 'Your Order start Cooking'), ('Dispatch', 'Your Order has been Dispatch'), ('Deliver', 'Your Order has been Delivered')], default='Accepted', max_length=100),
        ),
    ]
