# Generated by Django 3.0.7 on 2020-11-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0016_auto_20201126_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humpy_food_app.Menu'),
        ),
    ]
