# Generated by Django 3.0.7 on 2020-11-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0017_auto_20201126_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(max_length=200),
        ),
    ]
