# Generated by Django 3.0.7 on 2020-11-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0019_auto_20201126_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='menu',
            field=models.CharField(max_length=200),
        ),
    ]
