# Generated by Django 3.0.8 on 2020-11-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0021_auto_20201128_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='track',
            field=models.CharField(choices=[('Pending Seller Approval', 'Pending Seller Approval'), ('Your Order is Accepted', 'Your Order is Accepted'), ('Your Order start Cooking', 'Your Order start Cooking'), ('Your Order has been Dispatch', 'Your Order has been Dispatch'), ('Your Order has been Delivered', 'Your Order has been Delivered')], default='Pending Seller Approval', max_length=100),
        ),
    ]
