# Generated by Django 3.0.7 on 2020-12-03 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0023_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humpy_food_app.Menu'),
        ),
    ]
