# Generated by Django 3.0.7 on 2020-12-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0025_auto_20201205_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprofile',
            name='image',
            field=models.ImageField(blank=True, default='/static/images/log1.jpg', null=True, upload_to='image/'),
        ),
    ]
