# Generated by Django 3.0.7 on 2020-12-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0026_auto_20201205_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setprofile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/log.png', null=True, upload_to='image/'),
        ),
    ]
