# Generated by Django 3.0.8 on 2020-12-15 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('humpy_food_app', '0027_auto_20201205_1123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
